// Code generated by go-swagger; DO NOT EDIT.

package unique

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetUniqueLinkEmailParams creates a new GetUniqueLinkEmailParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetUniqueLinkEmailParams() *GetUniqueLinkEmailParams {
	return &GetUniqueLinkEmailParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetUniqueLinkEmailParamsWithTimeout creates a new GetUniqueLinkEmailParams object
// with the ability to set a timeout on a request.
func NewGetUniqueLinkEmailParamsWithTimeout(timeout time.Duration) *GetUniqueLinkEmailParams {
	return &GetUniqueLinkEmailParams{
		timeout: timeout,
	}
}

// NewGetUniqueLinkEmailParamsWithContext creates a new GetUniqueLinkEmailParams object
// with the ability to set a context for a request.
func NewGetUniqueLinkEmailParamsWithContext(ctx context.Context) *GetUniqueLinkEmailParams {
	return &GetUniqueLinkEmailParams{
		Context: ctx,
	}
}

// NewGetUniqueLinkEmailParamsWithHTTPClient creates a new GetUniqueLinkEmailParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetUniqueLinkEmailParamsWithHTTPClient(client *http.Client) *GetUniqueLinkEmailParams {
	return &GetUniqueLinkEmailParams{
		HTTPClient: client,
	}
}

/*
GetUniqueLinkEmailParams contains all the parameters to send to the API endpoint

	for the get unique link email operation.

	Typically these are written to a http.Request.
*/
type GetUniqueLinkEmailParams struct {

	// Email.
	Email string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get unique link email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUniqueLinkEmailParams) WithDefaults() *GetUniqueLinkEmailParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get unique link email params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetUniqueLinkEmailParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get unique link email params
func (o *GetUniqueLinkEmailParams) WithTimeout(timeout time.Duration) *GetUniqueLinkEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get unique link email params
func (o *GetUniqueLinkEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get unique link email params
func (o *GetUniqueLinkEmailParams) WithContext(ctx context.Context) *GetUniqueLinkEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get unique link email params
func (o *GetUniqueLinkEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get unique link email params
func (o *GetUniqueLinkEmailParams) WithHTTPClient(client *http.Client) *GetUniqueLinkEmailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get unique link email params
func (o *GetUniqueLinkEmailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEmail adds the email to the get unique link email params
func (o *GetUniqueLinkEmailParams) WithEmail(email string) *GetUniqueLinkEmailParams {
	o.SetEmail(email)
	return o
}

// SetEmail adds the email to the get unique link email params
func (o *GetUniqueLinkEmailParams) SetEmail(email string) {
	o.Email = email
}

// WriteToRequest writes these params to a swagger request
func (o *GetUniqueLinkEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param email
	if err := r.SetPathParam("email", o.Email); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
