// Code generated by go-swagger; DO NOT EDIT.

package unique

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostUniqueLinkLinkParams creates a new PostUniqueLinkLinkParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostUniqueLinkLinkParams() *PostUniqueLinkLinkParams {
	return &PostUniqueLinkLinkParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostUniqueLinkLinkParamsWithTimeout creates a new PostUniqueLinkLinkParams object
// with the ability to set a timeout on a request.
func NewPostUniqueLinkLinkParamsWithTimeout(timeout time.Duration) *PostUniqueLinkLinkParams {
	return &PostUniqueLinkLinkParams{
		timeout: timeout,
	}
}

// NewPostUniqueLinkLinkParamsWithContext creates a new PostUniqueLinkLinkParams object
// with the ability to set a context for a request.
func NewPostUniqueLinkLinkParamsWithContext(ctx context.Context) *PostUniqueLinkLinkParams {
	return &PostUniqueLinkLinkParams{
		Context: ctx,
	}
}

// NewPostUniqueLinkLinkParamsWithHTTPClient creates a new PostUniqueLinkLinkParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostUniqueLinkLinkParamsWithHTTPClient(client *http.Client) *PostUniqueLinkLinkParams {
	return &PostUniqueLinkLinkParams{
		HTTPClient: client,
	}
}

/*
PostUniqueLinkLinkParams contains all the parameters to send to the API endpoint

	for the post unique link link operation.

	Typically these are written to a http.Request.
*/
type PostUniqueLinkLinkParams struct {

	// Data.
	Data PostUniqueLinkLinkBody

	// Link.
	Link string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post unique link link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUniqueLinkLinkParams) WithDefaults() *PostUniqueLinkLinkParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post unique link link params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostUniqueLinkLinkParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post unique link link params
func (o *PostUniqueLinkLinkParams) WithTimeout(timeout time.Duration) *PostUniqueLinkLinkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post unique link link params
func (o *PostUniqueLinkLinkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post unique link link params
func (o *PostUniqueLinkLinkParams) WithContext(ctx context.Context) *PostUniqueLinkLinkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post unique link link params
func (o *PostUniqueLinkLinkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post unique link link params
func (o *PostUniqueLinkLinkParams) WithHTTPClient(client *http.Client) *PostUniqueLinkLinkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post unique link link params
func (o *PostUniqueLinkLinkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the post unique link link params
func (o *PostUniqueLinkLinkParams) WithData(data PostUniqueLinkLinkBody) *PostUniqueLinkLinkParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the post unique link link params
func (o *PostUniqueLinkLinkParams) SetData(data PostUniqueLinkLinkBody) {
	o.Data = data
}

// WithLink adds the link to the post unique link link params
func (o *PostUniqueLinkLinkParams) WithLink(link string) *PostUniqueLinkLinkParams {
	o.SetLink(link)
	return o
}

// SetLink adds the link to the post unique link link params
func (o *PostUniqueLinkLinkParams) SetLink(link string) {
	o.Link = link
}

// WriteToRequest writes these params to a swagger request
func (o *PostUniqueLinkLinkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	// path param link
	if err := r.SetPathParam("link", o.Link); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
