// Code generated by go-swagger; DO NOT EDIT.

package dummy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new dummy API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for dummy API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	GetV1Dummy(params *GetV1DummyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1DummyOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
GetV1Dummy dummies endpoint

dummy endpoint
*/
func (a *Client) GetV1Dummy(params *GetV1DummyParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*GetV1DummyOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetV1DummyParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "GetV1Dummy",
		Method:             "GET",
		PathPattern:        "/v1/dummy",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetV1DummyReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetV1DummyOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*GetV1DummyDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
