// Code generated by go-swagger; DO NOT EDIT.

package dummy

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1DummyParams creates a new GetV1DummyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1DummyParams() *GetV1DummyParams {
	return &GetV1DummyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1DummyParamsWithTimeout creates a new GetV1DummyParams object
// with the ability to set a timeout on a request.
func NewGetV1DummyParamsWithTimeout(timeout time.Duration) *GetV1DummyParams {
	return &GetV1DummyParams{
		timeout: timeout,
	}
}

// NewGetV1DummyParamsWithContext creates a new GetV1DummyParams object
// with the ability to set a context for a request.
func NewGetV1DummyParamsWithContext(ctx context.Context) *GetV1DummyParams {
	return &GetV1DummyParams{
		Context: ctx,
	}
}

// NewGetV1DummyParamsWithHTTPClient creates a new GetV1DummyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1DummyParamsWithHTTPClient(client *http.Client) *GetV1DummyParams {
	return &GetV1DummyParams{
		HTTPClient: client,
	}
}

/*
GetV1DummyParams contains all the parameters to send to the API endpoint

	for the get v1 dummy operation.

	Typically these are written to a http.Request.
*/
type GetV1DummyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 dummy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DummyParams) WithDefaults() *GetV1DummyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 dummy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1DummyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 dummy params
func (o *GetV1DummyParams) WithTimeout(timeout time.Duration) *GetV1DummyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 dummy params
func (o *GetV1DummyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 dummy params
func (o *GetV1DummyParams) WithContext(ctx context.Context) *GetV1DummyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 dummy params
func (o *GetV1DummyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 dummy params
func (o *GetV1DummyParams) WithHTTPClient(client *http.Client) *GetV1DummyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 dummy params
func (o *GetV1DummyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1DummyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
